language: php

php:
    - 5.4
    - 5.5
    - 5.6

env:
  - NEO_VERSION="2.1.5"
  - NEO_VERSION="2.1.6"
  - NEO_VERSION="2.2.0-M01"

before_install:
    - sudo apt-get update > /dev/null
    - wget dist.neo4j.org/neo4j-community-$NEO_VERSION-unix.tar.gz > null
    - tar -xzf neo4j-community-$NEO_VERSION-unix.tar.gz > null
    - neo4j-community-$NEO_VERSION/bin/neo4j start > null

before_script:
    - composer self-update
    - composer install --prefer-source --no-interaction
    - mv tests/database_settings.yml.dist tests/database_settings.yml

script:
    - curl -vvv X POST -d '{"password": "neo4j", "new_authorization_token" : "4287e44985b04c7536c523ca6ea8e67c"}' -H 'Content-Type: application/json' -i http://localhost:7474/user/neo4j/authorization_token
    - vendor/bin/phpunit

notifications:
    email: "willemsen.christophe@gmail.com"
