services:
  neoclient.connection_manager:
    class: "Neoxygen\\NeoClient\\Connection\\ConnectionManager"
    arguments: ["@?logger","@?event_dispatcher"]

  neoclient.command_manager:
    class: "Neoxygen\\NeoClient\\Command\\CommandManager"
    arguments: ["@?logger","@?event_dispatcher"]

  neoclient.http_client:
    class: "Neoxygen\\NeoClient\\HttpClient\\GuzzleHttpClient"
    arguments: ["%neoclient.response_format%","@?logger","@?event_dispatcher","@neoclient.connection_manager"]

  logger:
    class: "Neoxygen\\NeoClient\\Logger\\LoggerManager"

  neoclient.extension_manager:
    class: "Neoxygen\\NeoClient\\Extension\\ExtensionManager"
    arguments: ["@neoclient.command_manager"]

  event_dispatcher:
    class: "Symfony\\Component\\EventDispatcher\\ContainerAwareEventDispatcher"
    arguments: ["@service_container"]
