# Services definitions

services:
  neoclient.connection_manager:
    class: "Neoxygen\\NeoClient\\Connection\\ConnectionManager"

  neoclient.command_manager:
    class: "Neoxygen\\NeoClient\\Command\\CommandManager"

  neoclient.http_client:
    class: "Neoxygen\\NeoClient\\HttpClient\\GuzzleHttpClient"

  neoclient.logger_manager:
    class: "Neoxygen\\NeoClient\\Logger\\LoggerManager"